"""Fetch the full list of SET+mai listed stocks and write to data/tickers.txt.

Run once to refresh the ticker universe:
    python scripts/fetch_tickers.py

Tries SET's API with a browser-like session. Falls back to manual instructions
if the site blocks the request.
"""
import os
import sys
import time

import requests

OUT_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "tickers.txt")

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "th-TH,th;q=0.9,en-US;q=0.8,en;q=0.7",
    "Referer": "https://www.set.or.th/",
    "Origin": "https://www.set.or.th",
}

# Try these endpoints in order
ENDPOINTS = [
    {
        "url": "https://www.set.or.th/api/set/stock/list",
        "params": {"market": "SET,mai", "securityType": "S", "language": "en"},
        "key": "securitySymbols",
    },
    {
        "url": "https://www.set.or.th/api/set/stock/list",
        "params": {"market": "SET", "securityType": "S", "language": "en"},
        "key": "securitySymbols",
    },
]


def fetch_from_set_api() -> list[str]:
    session = requests.Session()
    session.headers.update(HEADERS)

    # Visit the page first to pick up session cookies
    print("  Getting session cookies...")
    session.get(
        "https://www.set.or.th/en/market/product/stock/quote/price.html",
        timeout=15,
    )
    time.sleep(1)

    for ep in ENDPOINTS:
        try:
            print(f"  Trying {ep['url']} ...")
            resp = session.get(ep["url"], params=ep["params"], timeout=20)
            resp.raise_for_status()
            data = resp.json()
            items = data.get(ep["key"]) or []
            if items:
                # Each item is a dict {"symbol": "PTT", ...}
                symbols = [
                    item["symbol"].strip().upper()
                    for item in items
                    if isinstance(item, dict) and item.get("symbol", "").strip()
                ]
                if symbols:
                    return symbols
        except Exception as e:
            print(f"  → failed: {e}")

    raise RuntimeError("All endpoints failed.")


def write_tickers(symbols: list[str]) -> None:
    lines = [
        "# Thai (SET+mai) ticker universe — auto-generated by scripts/fetch_tickers.py",
        "# Refresh periodically (SET100 rebalances semi-annually).",
        "",
    ]
    for sym in sorted(symbols):
        ticker = sym if sym.endswith(".BK") else f"{sym}.BK"
        lines.append(ticker)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nWrote {len(symbols)} tickers → {OUT_FILE}")


def manual_instructions() -> None:
    print(
        "\nAutomatic fetch failed. Get the full list manually:\n"
        "1. Go to https://www.set.or.th/en/market/product/stock/quote/price.html\n"
        "2. Click 'Download' (Excel/CSV) at the bottom of the table.\n"
        "3. Copy the symbol column into data/tickers.txt, one per line, with .BK suffix.\n"
        "   Example:  PTT.BK\n"
    )


if __name__ == "__main__":
    print("Fetching full SET+mai ticker list...")
    try:
        symbols = fetch_from_set_api()
        print(f"Found {len(symbols)} symbols.")
        write_tickers(symbols)
    except Exception as e:
        print(f"\nAll attempts failed: {e}")
        manual_instructions()
        sys.exit(1)
